apiVersion: v1
kind: Pod
metadata:
  name: "{{name}}"
  namespace: "{{namespace}}"
  labels:
    app: nodeshell
spec:
  nodeName: "{{node}}"
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: nodeshell
    image: "{{image}}"
    command: ["nsenter"]
    args: ["-t", "1", "-m", "-u", "-i", "-n", "sleep", "infinity"]
    workingDir: "/root"
    securityContext:
      privileged: true
