cmd = "kw"

editor = "$EDITOR"

source_file_path = "$HOME/.kube/.source_file"

[kubectl]
name = "kubectl"
args = []

[nodeshell]
namespace = "kube-system"
image = "alpine:latest"
shell = ["bash"]

[kubeconfig]
root = "$HOME/.kube/config"

[history]
path = "$HOME/.kube/.history"
max = 100
