name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Build Go
      run: make cross

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: |
            bin/*.tar.gz
